Add missing packages to requirements.txt
Exabyte-io/exabyte-api-examples pull request #27
Opened 2021-02-23 00:04 UTC by AcylSilane

2021-03-31 03:26 UTC, timurbazhirov commented
Let's add versions for the packages pls

2021-04-21 19:29 UTC, triplepoint requested changes
Repeating timur's comment: let's pin these versions specifically.

2021-04-21 19:50 UTC, AcylSilane commented
Forgot to update the versions here, only bumped them on the proof-of-concept workflow on the webapp - https://exabyte.atlassian.net/browse/SOF-4258?focusedCommentId=41385

2021-04-21 20:29 UTC, triplepoint approved these changes

2021-04-21 23:32 UTC, merged